### ISSUE TITLE
Next Release Checklist

### ISSUE THREAD

**Issue by exactlyallan** [rapidsai/cuxfilter#495]
Update List:

```[tasklist]
### Tasks
- [x] #487 Fix graph bug
- [x] #488 Remove datatiles
- [x] #492 Bokeh 3.0+ support
- [x] #494 Holoview charts
- [x] #484 hvPlot Js/CSS bug Fix
- [x] #450 CUDA 12 support
- [x] #491 pip install / wheel (ref: #497)
- [ ] https://github.com/rapidsai/cuxfilter/pull/516
- [ ] https://github.com/rapidsai/cuxfilter/issues/486
- [ ] https://github.com/rapidsai/cuxfilter/pull/514
- [ ] https://github.com/rapidsai/cuxfilter/pull/488
```
